export const ADD_INGRIDIENT = 'ADD_INGRIDIENT';
export const REMOVE_INGRIDIENT = 'REMOVE_INGRIDIENT';
export const SET_INGRIDIENTS = 'SET_INGRIDIENTS';
export const FETCH_INGRIDIENTS_FAILED = 'FETCH_INGRIDIENTS_FAILED';

export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_INIT = "PURCHASEPURCHASE_INIT_INIT";

export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const ADD_MENUITEMS = 'ADD_MENUITEMS';
export const EDIT_MENUITEMS = 'EDIT_MENUITEMS';
export const REMOVE_MENUITEMS = 'REMOVE_MENUITEMS';
export const SET_MENUITEMS = 'SET_MENUITEMS';
export const FETCH_MENUITEMS_FAILED = 'FETCH_MENUITEMS_FAILED';

export const ADD_STAFFITEMS = 'ADD_STAFFITEMS';
export const EDIT_STAFFITEMS = 'EDIT_STAFFITEMS';
export const REMOVE_STAFFITEMS = 'REMOVE_STAFFITEMS';
export const SET_STAFFITEMS = 'SET_STAFFITEMS';
export const FETCH_STAFFITEMS_FAILED = 'FETCH_STAFFITEMS_FAILED';

export const ADD_STOREITEMS = 'ADD_STOREITEMS';
export const EDIT_STOREITEMS = 'EDIT_STOREITEMS';
export const REMOVE_STOREITEMS = 'REMOVE_STOREITEMS';
export const SET_STOREITEMS = 'SET_STOREITEMS';
export const FETCH_STOREITEMS_FAILED = 'FETCH_STOREITEMS_FAILED';

export const ADD_CARTITEMS = 'ADD_CARTITEMS';
export const EDIT_CARTITEMS = 'EDIT_CARTITEMS';
export const REMOVE_CARTITEMS = 'REMOVE_CARTITEMS';
export const SET_CARTITEMS = 'SET_CARTITEMS';
export const FETCH_CARTITEMS_FAILED = 'FETCH_CARTITEMS_FAILED';


export const SET_CHECKOUTITEMS = 'SET_CHECKOUTITEMS';
export const FETCH_CHECKOUTITEMS_FAILED = 'FETCH_CHECKOUTITEMS_FAILED';
